

from django.urls import path
from myapp import views

urlpatterns=[
    path('login/', views.login_page, name='login_page'),
    path('login_post/', views.login_post, name='login_post'),
     
    
    path('add_category/', views.add_category, name='add_category'),
    path('add_facility/', views.add_facility, name='add_facility'),
    path('add_room/', views.add_room, name='add_room'),
    path('edit_facility/<id>', views.edit_facility, name='edit_facility'),
    path('delete_facility/<id>', views.delete_facility, name='delete_facility'),
    path('edit_room/<id>/', views.edit_room, name='edit_room'),
    path('view_category/', views.view_category, name='new_category'),
    path('delete_category/<id>/', views.delete_category, name='delete_category'),
    path('approve_provider/<id>/', views.approve_provider, name='approve_provider'),
    path('reject_provider/<id>/', views.reject_provider, name='reject_provider'),
    path('category_post/', views.category_post, name='category_post'),
    path('view_room/', views.view_room, name='view_room'),
    path('delete_room/<id>/', views.delete_room, name='delete_room'),
    path('add_room_post/',views.add_room_post),
    path('send_reply/', views.send_reply, name='send_reply'),
    path('verify_servicesprovider/', views.verify_servicesprovider, name='verify_servicesprovider'),
    path('view_complaint/', views.view_complaint, name='view_complaint'),
    path('reply_complaint/<id>/', views.reply_complaint, name='reply_complaint'),
    path('admin_view_facility/', views.admin_view_facility, name='view_facility'),
    path('view_rating/', views.view_rating, name='view_rating'),
    path('admin_home/', views.admin_home, name='admin_home'),
    path('verify_occupants/', views.verify_occupants, name='verify_occupants'),
    path('approve_occupant/<id>/', views.approve_occupant, name='approve_occupant'),
    path('reject_occupant/<id>/', views.reject_occupant, name='reject_occupant'),

    
    path('service_home/', views.service_home, name='service_home'),
    path('add_food/', views.add_food, name='add_food'),
    path('add_service/', views.add_service, name='add_service'),
    path('edit_fooditem/<id>/', views.edit_fooditem, name='edit_fooditem'),
    path('delete_fooditem/<id>/', views.delete_fooditem, name='delete_fooditem'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('service_provider_register/', views.service_provider_register, name='register'),
    path('register_post/', views.register_post, name='register_post'),
    path('send_complaint/', views.send_complaint, name='send_complaint'),
    path('view_fooditem/', views.view_fooditem, name='view_food_item'),
    path('view_profile/', views.view_profile, name='view_profile'),
    path('admin_view_rating/', views.admin_view_rating, name='view_rating'),
    path('view_reply/', views.view_reply, name='view_reply'),
    path('view_services/', views.view_services, name='view_services'),
    path('edit_service/<id>/', views.edit_service, name='edit_service'),
    path('delete_service/<id>/', views.delete_service, name='delete_service'),
    path('service_view_bookings/', views.service_view_bookings, name='service_view_bookings'),
    path('confirm_booking/<id>/', views.confirm_booking, name='confirm_booking'),
    path('reject_booking/<id>/', views.reject_booking, name='reject_booking'),
    path('service_view_food_orders/', views.service_view_food_orders, name='service_view_food_orders'),
    path('confirm_food_order/<id>/', views.confirm_food_order, name='confirm_food_order'),
    path('reject_food_order/<id>/', views.reject_food_order, name='reject_food_order'),
    path('pay_order/<id>/', views.pay_order, name='pay_order'),
    path('service_payment/<id>/', views.service_payment, name='service_payment'),
    path('send_service_rating/<id>/', views.send_service_rating, name='send_service_rating'),
    path('user_view_rating/<id>', views.user_view_rating, name='user_view_rating'),
    
    
    path('add_quantity/<id>/', views.add_quantity, name='add_quantity'),
    path('user_register_post/', views.user_register_post, name='user_register_post'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('user_register/', views.user_register, name='user_register'),
    path('send_complaint/', views.send_complaint, name='send_complaint'),
    path('user_view_booking/', views.user_view_booking, name='user_view_booking'),
    path('view_facility/', views.view_facility, name='view_facility'),
    path('user_view_fooditem/', views.user_view_fooditem, name='user_view_food_item'),
    path('user_view_profile/', views.user_view_profile, name='user_view_profile'),
    path('user_view_rating/', views.user_view_rating, name='user_view_rating'),
    path('user_view_reply/', views.user_view_reply, name='user_view_reply'),
    path('user_view_services/', views.user_view_services, name='user_view_services'),
    path('user_home/', views.user_home, name='user_home'),
    path('order_history/', views.order_history, name='order_history'),
    path('user_edit_profile/', views.user_edit_profile, name='user_edit_profile'),
    path('book_service/<id>/', views.book_service, name='book_service'),
    path('chat_with_user/<fid>/<fname>/', views.chat_with_user, name='chat_with_user'),
    path('chat_api/', views.chat_api, name='chat_api'),
]
